# TensorFlow 2
## Manipulação de tensores

In [1]:
# Carregar tensorflow
import tensorflow as tf

In [2]:
# Criar tensor e preencher com zeros
tensor = tf.zeros(shape=[3,4], dtype=tf.int32)
print(('Tensor preenchido com zeros como int32, 3 linhas e 4 colunas:\n{0}').format(tensor.numpy()))

Tensor preenchido com zeros como int32, 3 linhas e 4 colunas:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [3]:
tensor = tf.ones(shape = [5, 3], dtype = tf.float32)
print(('\nTensor preenchido com valor 1 e float32, 5 linhas e 3 colunas:\n{0}').format(tensor.numpy()))


Tensor preenchido com valor 1 e float32, 5 linhas e 3 colunas:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
tensor = tf.constant(100, shape = [4, 4], dtype = tf.float64)
print(('\nTensor preenchido com valor 100 e float64, 4 linhas e 4 colunas:\n{0}').format(tensor.numpy()))


Tensor preenchido com valor 100 e float64, 4 linhas e 4 colunas:
[[100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]]


In [5]:
tensor = tf.Variable(tf.zeros([1, 2]))
print(tensor)

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[0., 0.]], dtype=float32)>


In [6]:
# atribuir valores ao tensor criado na celula anterior
tensor.assign_add([[100, 200]])
print(tensor)

<tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[100., 200.]], dtype=float32)>


# Reshape

In [8]:
tensor = tf.constant([[3, 2],
                      [5, 2],
                      [9, 5],
                      [1, 3]])

print('\nShape do Tensor Original:', tensor.shape)
print('\nRank do Tensor Original:', tf.rank(tensor))
print(tensor.numpy())


Shape do Tensor Original: (4, 2)

Rank do Tensor Original: tf.Tensor(2, shape=(), dtype=int32)
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [9]:
# Remodelando o tensor em uma forma de: shape = [linhas, colunas]
tensor_reshaped = tf.reshape(tensor = tensor, shape = [1, 8])

In [10]:
tf.print('\nTensor antes do reshape:\n', tensor)

print(('\nTensor depois do reshape:\n{0}').format(tensor_reshaped.numpy()))

print('\nShape do Novo Tensor:', tensor_reshaped.shape)

print('\nRank do Novo Tensor:', tf.rank(tensor_reshaped))


Tensor antes do reshape:
 [[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tensor depois do reshape:
[[3 2 5 2 9 5 1 3]]

Shape do Novo Tensor: (1, 8)

Rank do Novo Tensor: tf.Tensor(2, shape=(), dtype=int32)


# Conversão de dados

In [11]:
tensor = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]], 
                      dtype = tf.float32)

In [12]:
# Convertendo o tensor de float32 para int32
tensor_de_inteiros = tf.cast(tensor, tf.int32)

# Arredonda os elementos do tensor
tensor_arredondado = tf.math.round(tensor)

In [13]:
tf.print('\nTensor com floats:\n', tensor)
tf.print('\nTipo de Dado do Tensor:\n', tensor.dtype)

tf.print('\nTensor cast de float para int (apenas remove o decimal, não faz arredondamento):\n', tensor_de_inteiros)
tf.print('\nTipo de Dado do Tensor:\n', tensor_de_inteiros.dtype)

tf.print('\nTensor com arrendodamento:\n', tensor_arredondado)
tf.print('\nTipo de Dado do Tensor:\n', tensor_arredondado.dtype)


Tensor com floats:
 [[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]

Tipo de Dado do Tensor:
 tf.float32

Tensor cast de float para int (apenas remove o decimal, não faz arredondamento):
 [[3 2]
 [5 2]
 [9 5]
 [1 3]]

Tipo de Dado do Tensor:
 tf.int32

Tensor com arrendodamento:
 [[3 3]
 [5 2]
 [10 6]
 [1 3]]

Tipo de Dado do Tensor:
 tf.float32
