# TensorFlow 2
## Slice e concatenar tensores

In [1]:
# Carregar tensorflow
import tensorflow as tf

# Slice

In [3]:
# Criar tensor variavel
tensor = tf.Variable([[1,2,3]
                     ,[4,5,6]])
print(tensor)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [4]:
slice_01 = tensor[1]
print(slice_01)

tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [5]:
slice_02 = tensor[1,2]
print(slice_02)

tf.Tensor(6, shape=(), dtype=int32)


In [6]:
slice_03 = tensor[:,2]
print(slice_03)

tf.Tensor([3 6], shape=(2,), dtype=int32)


In [7]:
slice_04 = tensor[0:1,1:2]
print(slice_04)

tf.Tensor([[2]], shape=(1, 1), dtype=int32)


# Concatenar

In [8]:
# criar tensores contantes
t1 = tf.constant([[3,2]
                 ,[5,2]])
t2 = tf.constant([[1,9]
                ,[2,8]])

print(t1)
print(t2)

tf.Tensor(
[[3 2]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 9]
 [2 8]], shape=(2, 2), dtype=int32)


In [9]:
# Colunas
t1_t2_concat_col = tf.concat(values=[t1,t2], axis=1)
print(t1_t2_concat_col)

tf.Tensor(
[[3 2 1 9]
 [5 2 2 8]], shape=(2, 4), dtype=int32)


In [10]:
# Linhas
t1_t2_concat_lin = tf.concat(values=[t1,t2], axis=0)
print(t1_t2_concat_lin)

tf.Tensor(
[[3 2]
 [5 2]
 [1 9]
 [2 8]], shape=(4, 2), dtype=int32)
