# TensorFlow 2
## Variáveis no Tensorflow

- Variáveis no TensorFlow são como variáveis em qualquer outra linguagem.

In [1]:
# Carregar tensorflow
import tensorflow as tf

In [2]:
# Operação no python
x = 8
y = x + 2

print(y)

10


In [3]:
# Operacao no TF
x = tf.constant(1)
y = tf.Variable(x + 9)

print(y)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>


In [4]:
# Operação de adição em tensores
tensor_a = tf.Variable([[1, 2, 2], [3, 4, 2]], dtype = tf.int32)
print('Tensor a:', tensor_a)
print('Rank Tensor a:', tf.rank(tensor_a))
print("\n")

tensor_b = tf.Variable([[5, 6, 7]], dtype = tf.int32)
print('Tensor b:', tensor_b)
print('Rank Tensor b:', tf.rank(tensor_b))
print("\n")

tensor_add = tf.add(tensor_a, tensor_b)
print('Tensor_add:', tensor_add)
print('Rank Tensor_add:', tf.rank(tensor_add))

print("\n")

Tensor a: <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 2],
       [3, 4, 2]], dtype=int32)>
Rank Tensor a: tf.Tensor(2, shape=(), dtype=int32)


Tensor b: <tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[5, 6, 7]], dtype=int32)>
Rank Tensor b: tf.Tensor(2, shape=(), dtype=int32)


Tensor_add: tf.Tensor(
[[ 6  8  9]
 [ 8 10  9]], shape=(2, 3), dtype=int32)
Rank Tensor_add: tf.Tensor(2, shape=(), dtype=int32)


