# TensorFlow 2
## Estrutura e comandos básicos

In [1]:
# Carregar tensorflow
import tensorflow as tf

In [2]:
# Hello Wordl
hello = tf.constant('Hello World')
print(hello)
tf.print(hello)

tf.Tensor(b'Hello World', shape=(), dtype=string)
Hello World


- O TensorFlow armazena dados em Tensores que são semelhantes a arrays multidimensionais do numPy 
- Os dados não são armazenados como inteiros, floats ou strings de caracteres, são encapsulados em um objeto chamado de tensor. 

## Dimensões e Rank

#### Rank	     Math entity
- 0	Scalar   (somente magnitude)
- 1	Vector   (magnitude e direção)
- 2	Matrix   (tabela)
- 3	3-Tensor (cubo)
- n	n-Tensor (n-dimensões)

In [3]:
# tensor 0-dimensional string - Rank 0
hello = tf.constant('Hello World!')
print("Rank:", tf.rank(hello))

Rank: tf.Tensor(0, shape=(), dtype=int32)


In [4]:
# tensor 0-dimensional int32 (escalar) - Rank 0
t1 = tf.constant(1234)
print(t1)
print("Rank:", tf.rank(t1))

tf.Tensor(1234, shape=(), dtype=int32)
Rank: tf.Tensor(0, shape=(), dtype=int32)


In [5]:
# tensor 1-dimensional float32 - Rank 1
t2 = tf.constant([123,456,789], dtype = tf.float32) 
print(t2)
print("Rank:", tf.rank(t2))

tf.Tensor([123. 456. 789.], shape=(3,), dtype=float32)
Rank: tf.Tensor(1, shape=(), dtype=int32)


In [6]:
# tensor 2-dimensional int16 - Rank 2
t3 = tf.constant([ [123, 456, 789], [222, 333, 444] ], dtype = tf.int16)    
print(t3)
print("Rank:", tf.rank(t3))

tf.Tensor(
[[123 456 789]
 [222 333 444]], shape=(2, 3), dtype=int16)
Rank: tf.Tensor(2, shape=(), dtype=int32)


In [7]:
# tensor 3-dimensional int32 - - Rank 3
t4 = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])   
print(t4)
print("Rank:", tf.rank(t4))

tf.Tensor(
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]], shape=(2, 2, 3), dtype=int32)
Rank: tf.Tensor(3, shape=(), dtype=int32)
