# Exercícios de Matrizes com TF
Lista de exercícios sugeridos no curso Deep Learning Framework da formação Inteligência Artificial da Data Science Academy

In [1]:
# Carregar pacotes
import numpy as np
import tensorflow as tf

In [3]:
# Criar uma matriz identidade 3x3
m_identidade = tf.eye(3, num_columns = 3)
print(m_identidade)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [13]:
# Criar uma matriz 2x3 randomicamente normalizada
m_rand_norm = tf.random.truncated_normal([2,3])
print(m_rand_norm)

tf.Tensor(
[[0.3336924  0.00667806 0.09010551]
 [0.5521129  1.7177782  0.8119811 ]], shape=(2, 3), dtype=float32)


In [14]:
# Criar uma matriz 2x3 com valores constantes
m_const_val = tf.fill([2,3], 10.)
print(m_const_val)

tf.Tensor(
[[10. 10. 10.]
 [10. 10. 10.]], shape=(2, 3), dtype=float32)


In [17]:
# Criar uma matriz 3x2 randomicamente uniforme
m_rand_unif = tf.random.uniform([3,2])
print(m_rand_unif)

tf.Tensor(
[[0.6888585  0.62952936]
 [0.41823566 0.47840643]
 [0.43536437 0.78705096]], shape=(3, 2), dtype=float32)


In [9]:
# Converter um array numpy 3x3 para um tensor
array_np = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
tensor_array = tf.convert_to_tensor(array_np)
print(array_np)
print(tensor_array)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float64)


In [15]:
# Somar matrizes
print(m_rand_norm + m_const_val)

tf.Tensor(
[[10.333693 10.006678 10.090105]
 [10.552113 11.717778 10.811981]], shape=(2, 3), dtype=float32)


In [16]:
# Subtrair matrizes
print(m_const_val - m_const_val)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [18]:
# Multiplicar matrizes
print(tf.matmul(m_rand_norm, m_rand_unif))

tf.Tensor(
[[0.27188858 0.28418162]
 [1.4522713  1.8084378 ]], shape=(2, 2), dtype=float32)


In [19]:
# Transposta da matriz rand_unif
print(tf.transpose(m_rand_unif))

tf.Tensor(
[[0.6888585  0.41823566 0.43536437]
 [0.62952936 0.47840643 0.78705096]], shape=(2, 3), dtype=float32)


In [20]:
# Determinante da matriz tensor_array
print(tf.linalg.det(tensor_array))

tf.Tensor(6.66133814775094e-16, shape=(), dtype=float64)


In [21]:
# Matrix Inversa da matriz tensor_array
print(tf.linalg.inv(tensor_array))

tf.Tensor(
[[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]], shape=(3, 3), dtype=float64)
