# Exercícios com Tensores no TF
Lista de exercícios do curos Deep Learning Framework da Formação Inteligência Artificial da Data Sciecen Academy

In [2]:
# Carregar pacotes
import tensorflow as tf

In [3]:
# Cria um tensor preenchido por 20 zeros, dimensão 1x20
tensor = tf.zeros([1,20])
print(tensor)

tf.Tensor([[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(1, 20), dtype=float32)


In [10]:
# Declarar uma variável que recebe um tensor preenchido por 20 zeros
var_tensor = tf.Variable(tf.zeros([1,20]), dtype=tf.float32)
print(var_tensor)

<tf.Variable 'Variable:0' shape=(1, 20) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)>


In [11]:
# Criar Tensor inicializado com zeros usando como dimensões as variáveis python
row_dim = 4
col_dim = 8

tensor_zero = tf.Variable(tf.zeros([row_dim, col_dim]))
print(tensor_zero)

<tf.Variable 'Variable:0' shape=(4, 8) dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>


In [12]:
# Criar Tensor inicializado com 1 usando como dimensões as variáveis python
row_dim = 2
col_dim = 4

tensor_one = tf.Variable(tf.ones([row_dim, col_dim]))
print(tensor_one)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>


In [14]:
# Tensor preenchido com valores constantes (variáveis Python)
row_dim = 10
col_dim = 2

tensor_fill = tf.Variable(tf.fill([row_dim, col_dim], 10))
print(tensor_fill)

<tf.Variable 'Variable:0' shape=(10, 2) dtype=int32, numpy=
array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]], dtype=int32)>


In [15]:
# Cria um tensor a partir de uma lista de valores constantes
tensor_const = tf.Variable(tf.constant([1,2,3,4,5]))
print(tensor_const)

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>


In [16]:
# Cria um tensor a partir de uma lista de valores constantes com variáveis python
row_dim = 2
col_dim = 2

tensor_const_fill = tf.Variable(tf.constant(10, shape = [row_dim,col_dim]))
print(tensor_const_fill)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 10],
       [10, 10]], dtype=int32)>


In [17]:
# Gerando uma sequência de valores lineares com a função tf.linspace, 
#começando por 0.0, terminando em 1.0, com 3 elementos
tensor_linear = tf.Variable(tf.linspace(start = 0.0, stop = 1.0, num = 3))
print(tensor_linear)

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0. , 0.5, 1. ], dtype=float32)>


In [18]:
# Gerando uma sequência de valores com a função tf.range, 
#começando por 6, limite de 15 e saltando de 3 em 3
tensor_sequence = tf.Variable(tf.range(start = 6, limit = 15, delta = 3))
print(tensor_sequence)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 6,  9, 12], dtype=int32)>
