# Operações com Tensores

In [1]:
import numpy as np
import tensorflow as tf

In [4]:
array1 = np.array([(1,2),(3,4)], dtype = 'int32') 
array2 = np.array([(5,6),(7,8)], dtype = 'int32')
array3 = np.array([(2,7,2),(1,4,2),(9,0,2)], dtype = 'float32') 
array4 = np.array([[[1,2,3,4],[3,4,5,6]],[[5,6,7,8],[7,8,9,0]],[[1,3,5,7],[2,4,6,8]]]) 

print ("\n--------Array 1--------") 
print (array1)
print ("\n--------Array 2--------") 
print (array2)
print ("\n--------Array 3--------") 
print (array3)
print ("\n--------Array 4--------") 
print (array4)


--------Array 1--------
[[1 2]
 [3 4]]

--------Array 2--------
[[5 6]
 [7 8]]

--------Array 3--------
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]

--------Array 4--------
[[[1 2 3 4]
  [3 4 5 6]]

 [[5 6 7 8]
  [7 8 9 0]]

 [[1 3 5 7]
  [2 4 6 8]]]


In [5]:
# Multiplicação das matrizes 1 e 2
matrix_product = tf.matmul(array1, array2)
print (matrix_product) 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [6]:
# Soma das matrizes 1 e 2
matrix_sum = tf.add(array1, array2)
print(matrix_sum)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [10]:
# Cálculo do determinate da matriz 3
matrix_det = tf.linalg.det(array3)
print(matrix_det)

tf.Tensor(55.999992, shape=(), dtype=float32)


In [11]:
# Calculando a raiz quadrada dos elementos do array 4
tf_tensor_3d = tf.convert_to_tensor(array4, dtype = tf.float64)
matrix_sqrt = tf.math.sqrt(tf_tensor_3d)
print(matrix_sqrt)

tf.Tensor(
[[[1.         1.41421356 1.73205081 2.        ]
  [1.73205081 2.         2.23606798 2.44948974]]

 [[2.23606798 2.44948974 2.64575131 2.82842712]
  [2.64575131 2.82842712 3.         0.        ]]

 [[1.         1.73205081 2.23606798 2.64575131]
  [1.41421356 2.         2.44948974 2.82842712]]], shape=(3, 2, 4), dtype=float64)
