# Tensores

- Tensores são as estruturas de dados básicas no TensorFlow. 
- Identifica uma matriz ou lista multidimensional.

- Identificado por três parâmetros, rank, shape e type: 

    - rank: Cada tensor é descrito por uma unidade de dimensionalidade chamada rank, que identifica o número de dimensões do tensor. 
    - Shape: A forma de um tensor é o número de linhas e colunas que ele possui. 

    - Type: É o tipo de dados atribuído aos elementos do tensor.

In [1]:
# Carregar pacotes
import numpy as np
import tensorflow as tf

## Unidimensionais

In [3]:
tensor_1d = np.array([1.2,2,4.0,22.11])

In [5]:
print(tensor_1d)
print(tensor_1d[0])
print(tensor_1d[1])

[ 1.2   2.    4.   22.11]
1.2
2.0


In [7]:
# Converter o arrya numpy em tensorflow
tf_tensor_1d = tf.convert_to_tensor(tensor_1d, dtype=tf.float64)

In [8]:
print(tf_tensor_1d)
print(tf_tensor_1d[0])
print(tf_tensor_1d[1])

tf.Tensor([ 1.2   2.    4.   22.11], shape=(4,), dtype=float64)
tf.Tensor(1.2, shape=(), dtype=float64)
tf.Tensor(2.0, shape=(), dtype=float64)


## Bidimensionais

In [9]:
tensor_2d = np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])

In [14]:
print(tensor_2d)
print(tensor_2d[2][2])
print(tensor_2d[0:2,0:2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
[[1 2]
 [4 5]]


In [15]:
# Converter o arrya numpy em tensorflow
tf_tensor_2d = tf.convert_to_tensor(tensor_2d, dtype=tf.float64)

In [16]:
print(tf_tensor_2d)
print(tf_tensor_2d[2][2])
print(tf_tensor_2d[0:2,0:2])

tf.Tensor(
[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]], shape=(4, 4), dtype=float64)
tf.Tensor(10.0, shape=(), dtype=float64)
tf.Tensor(
[[1. 2.]
 [4. 5.]], shape=(2, 2), dtype=float64)


## Tridimensionais

In [17]:
# Cria o array tridimensional
# Dimensões: (panel, row, col)
tensor_3d = np.array([[[1,2,3,4],[3,4,5,6]],[[5,6,7,8],[7,8,9,0]],[[1,3,5,7],[2,4,6,8]]]) 

In [22]:
print(tensor_3d.shape, "\n------")
print(tensor_3d)

(3, 2, 4) 
------
[[[1 2 3 4]
  [3 4 5 6]]

 [[5 6 7 8]
  [7 8 9 0]]

 [[1 3 5 7]
  [2 4 6 8]]]


In [23]:
# Elementos do array 3-D
print ('\nElemento do Array Numpy 3-D no índice [0,0,0]:', tensor_3d[0,0,0])
print ('\nElemento do Array Numpy 3-D no índice [0,1,1]:', tensor_3d[0,1,1])
print ('\nElemento do Array Numpy 3-D no índice [:, 0, 0]:', tensor_3d[:, 0, 0])


Elemento do Array Numpy 3-D no índice [0,0,0]: 1

Elemento do Array Numpy 3-D no índice [0,1,1]: 4

Elemento do Array Numpy 3-D no índice [:, 0, 0]: [1 5 1]


In [24]:
# Convertendo o array numpy para tensorflow
tf_tensor_3d = tf.convert_to_tensor(tensor_3d, dtype = tf.float64)

In [25]:
print(tf_tensor_3d.shape, "\n------")
print(tf_tensor_3d)

(3, 2, 4) 
------
tf.Tensor(
[[[1. 2. 3. 4.]
  [3. 4. 5. 6.]]

 [[5. 6. 7. 8.]
  [7. 8. 9. 0.]]

 [[1. 3. 5. 7.]
  [2. 4. 6. 8.]]], shape=(3, 2, 4), dtype=float64)


In [26]:
print ('\nElemento do Tensor 3-D no índice [0,0,0]:', tf_tensor_3d[0,0,0])
print ('\nElemento do Tensor 3-D no índice [0,1,1]:', tf_tensor_3d[0,1,1])
print ('\nElemento do Tensor 3-D no índice [:, 0, 0]:', tf_tensor_3d[:, 0, 0])


Elemento do Tensor 3-D no índice [0,0,0]: tf.Tensor(1.0, shape=(), dtype=float64)

Elemento do Tensor 3-D no índice [0,1,1]: tf.Tensor(4.0, shape=(), dtype=float64)

Elemento do Tensor 3-D no índice [:, 0, 0]: tf.Tensor([1. 5. 1.], shape=(3,), dtype=float64)
